version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 -js --server_name N1 --routes nats://nats-1:6222,nats://nats-2:6222"
    networks: ["nats"]
  nats-1:
    image: nats
    ports:
      - "4223:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -js --server_name N2 --routes nats://nats:6222,nats://nats-2:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    ports:
      - "4224:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -js --server_name N3 --routes nats://nats:6222,nats://nats-1:6222"
    networks: ["nats"]
    depends_on: ["nats"]

networks:
  nats:
    name: nats
