
version: '3'
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    ports:
    - "2181:2181"

  kafka1:
    image: wurstmeister/kafka
    environment:
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.3.153:9091
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=1
    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092
    - ZOOKEEPER=zookeeper:2181
    depends_on:
    - zookeeper
    ports:
    - '9091:9091'
    volumes:
      - "/tmp/kafka1:/kafka"


  kafka2:
    image: wurstmeister/kafka
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=PLAINTEXT://192.168.3.153:9092
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_BROKER_ID=2
    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092
    - ZOOKEEPER=zookeeper:2181
    depends_on:
    - zookeeper
    ports:
    - '9092:9092'
    volumes:
      - "/tmp/kafka1:/kafka"
